// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task/task.proto

package go_micro_service_task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{2}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{3}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{4}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{5}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Task struct {
	//每条任务的ID，本项目中对应mongodb记录的"_id"字段
	//@inject_tag: bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	//任务主体文字
	//@inject_tag: bson:"body"
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty" bson:"body"`
	//用户设定的任务开始时间戳
	//@inject_tag: bson:"startTime"
	StartTime int64 `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty" bson:"startTime"`
	//用户设定的任务截止时间戳
	//@inject_tag: bson:"endTime"
	EndTime int64 `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty" bson:"endTime"`
	//任务是否已完成
	//@inject_tag: bson:"isFinished"
	IsFinished int32 `protobuf:"varint,5,opt,name=isFinished,proto3" json:"isFinished,omitempty" bson:"isFinished"`
	//用户实际完成时间戳
	//@inject_tag: bson:"finishTime"
	FinishTime int64 `protobuf:"varint,6,opt,name=finishTime,proto3" json:"finishTime,omitempty" bson:"finishTime"`
	//任务创建时间
	//@inject_tag: bson:"createTime"
	CreateTime int64 `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty" bson:"createTime"`
	//任务修改时间
	//@inject_tag: bson:"updateTime"
	UpdateTime int64 `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime,omitempty" bson:"updateTime"`
	//用户ID
	//@inject_tag: bson:"userId"
	UserId               string   `protobuf:"bytes,9,opt,name=userId,proto3" json:"userId,omitempty" bson:"userId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{6}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Task) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Task) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Task) GetIsFinished() int32 {
	if m != nil {
		return m.IsFinished
	}
	return 0
}

func (m *Task) GetFinishTime() int64 {
	if m != nil {
		return m.FinishTime
	}
	return 0
}

func (m *Task) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Task) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Task) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//增删改接口返回参数
type EditResponse struct {
	//操作返回的消息
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{7}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//查询接口的参数
type SearchRequest struct {
	//分页查询页码，从第一页开始
	PageSize int64 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//分页查询每页数量，默认20
	PageCode int64 `protobuf:"varint,2,opt,name=pageCode,proto3" json:"pageCode,omitempty"`
	// 排序字段
	SortBy string `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	// 顺序 -1降序 1升序
	Order int32 `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	//关键字模糊查询任务body字段
	Keyword              string   `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{8}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchRequest) GetPageCode() int64 {
	if m != nil {
		return m.PageCode
	}
	return 0
}

func (m *SearchRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *SearchRequest) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *SearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SearchResponse struct {
	//分页查询页码，从第一页开始
	PageSize int64 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//分页查询每页数量，默认20
	PageCode int64 `protobuf:"varint,2,opt,name=pageCode,proto3" json:"pageCode,omitempty"`
	// 排序字段
	SortBy string `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	// 顺序 -1降序 1升序
	Order int32 `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	//数据总数
	Total int64 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	//具体数据，这里repeated表示可以出现多条，类似于go中的slice
	Rows                 []*Task  `protobuf:"bytes,6,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{9}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchResponse) GetPageCode() int64 {
	if m != nil {
		return m.PageCode
	}
	return 0
}

func (m *SearchResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *SearchResponse) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *SearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchResponse) GetRows() []*Task {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.service.task.Message")
	proto.RegisterType((*Response)(nil), "go.micro.service.task.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.service.task.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.service.task.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.service.task.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.service.task.Pong")
	proto.RegisterType((*Task)(nil), "go.micro.service.task.Task")
	proto.RegisterType((*EditResponse)(nil), "go.micro.service.task.EditResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.service.task.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.service.task.SearchResponse")
}

func init() {
	proto.RegisterFile("proto/task/task.proto", fileDescriptor_152e577c5c92a6d4)
}

var fileDescriptor_152e577c5c92a6d4 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xe1, 0x6e, 0xd3, 0x40,
	0x0c, 0xc7, 0x97, 0x36, 0x4d, 0x5b, 0x0f, 0xa6, 0x71, 0xda, 0x50, 0xd4, 0x4d, 0x53, 0x15, 0x40,
	0x84, 0x2f, 0xd9, 0x34, 0xde, 0x80, 0x01, 0x12, 0x88, 0x21, 0x74, 0x9d, 0xc4, 0x47, 0x74, 0xeb,
	0x79, 0xd9, 0xa9, 0x6b, 0xae, 0xdc, 0x5d, 0x99, 0xca, 0x4b, 0xf0, 0x44, 0x3c, 0x02, 0x2f, 0xc4,
	0x27, 0x74, 0x4e, 0xd2, 0x16, 0xb4, 0x76, 0x5f, 0x2a, 0xbe, 0x54, 0xf7, 0xf7, 0xcf, 0xb6, 0x1c,
	0xdb, 0x35, 0xec, 0x4f, 0x8c, 0x76, 0xfa, 0xd8, 0x09, 0x3b, 0xa2, 0x9f, 0x8c, 0x34, 0xdb, 0xcf,
	0x75, 0x36, 0x56, 0x43, 0xa3, 0x33, 0x8b, 0xe6, 0x9b, 0x1a, 0x62, 0xe6, 0x61, 0x72, 0x00, 0xed,
	0x73, 0xb4, 0x56, 0xe4, 0xc8, 0x76, 0xa1, 0x69, 0xc5, 0x2c, 0x0e, 0xfa, 0x41, 0xda, 0xe5, 0xfe,
	0x99, 0x1c, 0x42, 0x87, 0xa3, 0x9d, 0xe8, 0xc2, 0x12, 0x1d, 0xdb, 0xbc, 0xa6, 0x63, 0x9b, 0x27,
	0x29, 0xec, 0x0e, 0x9c, 0x41, 0x31, 0x56, 0x45, 0xce, 0xf1, 0xeb, 0x14, 0xad, 0x63, 0x7b, 0xd0,
	0x1a, 0xea, 0x69, 0xe1, 0xc8, 0xaf, 0xc9, 0x4b, 0x91, 0xbc, 0x80, 0x47, 0x4b, 0x9e, 0x55, 0xc2,
	0xbb, 0x5d, 0x8f, 0x20, 0xfc, 0xa4, 0x8a, 0x9c, 0x3d, 0x86, 0xc8, 0x3a, 0xa3, 0x47, 0x58, 0xe1,
	0x4a, 0x11, 0xd7, 0x6b, 0xf8, 0xef, 0x00, 0xc2, 0x0b, 0x61, 0x47, 0x6c, 0x07, 0x1a, 0x4a, 0x56,
	0xe5, 0x36, 0x94, 0x64, 0x0c, 0xc2, 0x4b, 0x2d, 0x67, 0x71, 0x83, 0x2c, 0xf4, 0x66, 0x87, 0xd0,
	0xb5, 0x4e, 0x18, 0x77, 0xa1, 0xc6, 0x18, 0x37, 0x29, 0xcf, 0xc2, 0xc0, 0x62, 0x68, 0x63, 0x21,
	0x89, 0x85, 0xc4, 0x6a, 0xc9, 0x8e, 0x00, 0x94, 0x7d, 0xab, 0x0a, 0x65, 0xaf, 0x51, 0xc6, 0xad,
	0x7e, 0x90, 0xb6, 0xf8, 0x92, 0xc5, 0xf3, 0x2b, 0x7a, 0x53, 0x70, 0x44, 0xc1, 0x4b, 0x16, 0xcf,
	0x87, 0x06, 0x85, 0x43, 0xe2, 0xed, 0x92, 0x2f, 0x2c, 0x9e, 0x4f, 0x27, 0xb2, 0xe6, 0x9d, 0x92,
	0x2f, 0x2c, 0xfe, 0xe3, 0xa7, 0x16, 0xcd, 0x3b, 0x19, 0x77, 0xe9, 0x6b, 0x2a, 0x95, 0xf4, 0xe1,
	0xc1, 0x1b, 0xa9, 0xdc, 0x9a, 0x99, 0xfd, 0x08, 0xe0, 0xe1, 0x00, 0x85, 0x19, 0x5e, 0xd7, 0x13,
	0xeb, 0x41, 0x67, 0x22, 0x72, 0x1c, 0xa8, 0xef, 0x75, 0x2b, 0xe7, 0xba, 0x66, 0x67, 0x5a, 0x22,
	0xf5, 0xad, 0x62, 0x5e, 0xd3, 0x00, 0xb4, 0x71, 0xaf, 0x66, 0xd4, 0xb8, 0x2e, 0xaf, 0x94, 0x1f,
	0xab, 0x36, 0x12, 0x0d, 0xf5, 0xac, 0xc5, 0x4b, 0xe1, 0x7b, 0x39, 0xc2, 0xd9, 0xad, 0x36, 0x65,
	0xbb, 0xba, 0xbc, 0x96, 0xc9, 0xcf, 0x00, 0x76, 0xea, 0x8a, 0xaa, 0xb2, 0xff, 0x4f, 0x49, 0x7b,
	0xd0, 0x72, 0xda, 0x89, 0x1b, 0x2a, 0xa8, 0xc9, 0x4b, 0xc1, 0x8e, 0x21, 0x34, 0xfa, 0xd6, 0xc6,
	0x51, 0xbf, 0x99, 0x6e, 0x9f, 0x1e, 0x64, 0x77, 0xfe, 0x6b, 0x32, 0xbf, 0x61, 0x9c, 0x1c, 0x4f,
	0x7f, 0x85, 0xb0, 0xed, 0xe5, 0xa0, 0xe4, 0xec, 0x03, 0x44, 0x67, 0x34, 0x49, 0xb6, 0x2e, 0xb8,
	0xf7, 0x64, 0x05, 0x5c, 0x9e, 0x5f, 0xb2, 0xe5, 0xb3, 0xbd, 0xc6, 0x1b, 0xdc, 0x5c, 0xb6, 0x73,
	0x2d, 0xd5, 0xd5, 0x6c, 0x23, 0xd9, 0x3e, 0x42, 0x67, 0xbe, 0xf1, 0x9b, 0xc8, 0xf7, 0x19, 0xa2,
	0x72, 0x11, 0xd8, 0xd3, 0x15, 0x01, 0x7f, 0x6d, 0x6e, 0xef, 0xd9, 0x3d, 0x5e, 0xf3, 0xc4, 0x5f,
	0x20, 0x2a, 0xcf, 0x0f, 0x7b, 0xbe, 0x2a, 0xe4, 0x9f, 0x3b, 0xd6, 0x4b, 0xef, 0x77, 0xac, 0xd3,
	0x9f, 0x04, 0xec, 0x3d, 0x74, 0xfc, 0xd1, 0xa2, 0xc3, 0xb4, 0xaa, 0x13, 0xde, 0xa1, 0xb7, 0x12,
	0xea, 0x22, 0x4f, 0xb6, 0xd2, 0xe0, 0x24, 0xb8, 0x8c, 0xe8, 0x5c, 0xbf, 0xfc, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x47, 0x74, 0x6a, 0xc7, 0x05, 0x00, 0x00,
}
