// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/task/task.proto

package go_micro_service_task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TaskService service

func NewTaskServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TaskService service

type TaskService interface {
	Create(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error)
	Delete(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error)
	Modify(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error)
	Finished(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TaskService_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (TaskService_PingPongService, error)
}

type taskService struct {
	c    client.Client
	name string
}

func NewTaskService(name string, c client.Client) TaskService {
	return &taskService{
		c:    c,
		name: name,
	}
}

func (c *taskService) Create(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "TaskService.Create", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Delete(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "TaskService.Delete", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Modify(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "TaskService.Modify", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Finished(ctx context.Context, in *Task, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "TaskService.Finished", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "TaskService.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TaskService_StreamService, error) {
	req := c.c.NewRequest(c.name, "TaskService.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &taskServiceStream{stream}, nil
}

type TaskService_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type taskServiceStream struct {
	stream client.Stream
}

func (x *taskServiceStream) Close() error {
	return x.stream.Close()
}

func (x *taskServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *taskServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *taskServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *taskServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskService) PingPong(ctx context.Context, opts ...client.CallOption) (TaskService_PingPongService, error) {
	req := c.c.NewRequest(c.name, "TaskService.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &taskServicePingPong{stream}, nil
}

type TaskService_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type taskServicePingPong struct {
	stream client.Stream
}

func (x *taskServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *taskServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *taskServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *taskServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *taskServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *taskServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TaskService service

type TaskServiceHandler interface {
	Create(context.Context, *Task, *EditResponse) error
	Delete(context.Context, *Task, *EditResponse) error
	Modify(context.Context, *Task, *EditResponse) error
	Finished(context.Context, *Task, *EditResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Stream(context.Context, *StreamingRequest, TaskService_StreamStream) error
	PingPong(context.Context, TaskService_PingPongStream) error
}

func RegisterTaskServiceHandler(s server.Server, hdlr TaskServiceHandler, opts ...server.HandlerOption) error {
	type taskService interface {
		Create(ctx context.Context, in *Task, out *EditResponse) error
		Delete(ctx context.Context, in *Task, out *EditResponse) error
		Modify(ctx context.Context, in *Task, out *EditResponse) error
		Finished(ctx context.Context, in *Task, out *EditResponse) error
		Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type TaskService struct {
		taskService
	}
	h := &taskServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TaskService{h}, opts...))
}

type taskServiceHandler struct {
	TaskServiceHandler
}

func (h *taskServiceHandler) Create(ctx context.Context, in *Task, out *EditResponse) error {
	return h.TaskServiceHandler.Create(ctx, in, out)
}

func (h *taskServiceHandler) Delete(ctx context.Context, in *Task, out *EditResponse) error {
	return h.TaskServiceHandler.Delete(ctx, in, out)
}

func (h *taskServiceHandler) Modify(ctx context.Context, in *Task, out *EditResponse) error {
	return h.TaskServiceHandler.Modify(ctx, in, out)
}

func (h *taskServiceHandler) Finished(ctx context.Context, in *Task, out *EditResponse) error {
	return h.TaskServiceHandler.Finished(ctx, in, out)
}

func (h *taskServiceHandler) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.TaskServiceHandler.Search(ctx, in, out)
}

func (h *taskServiceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TaskServiceHandler.Stream(ctx, m, &taskServiceStreamStream{stream})
}

type TaskService_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type taskServiceStreamStream struct {
	stream server.Stream
}

func (x *taskServiceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *taskServiceStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *taskServiceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *taskServiceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *taskServiceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *taskServiceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TaskServiceHandler.PingPong(ctx, &taskServicePingPongStream{stream})
}

type TaskService_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type taskServicePingPongStream struct {
	stream server.Stream
}

func (x *taskServicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *taskServicePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *taskServicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *taskServicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *taskServicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *taskServicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
